// PAIN CONSTANTS

var painIntensity = [
  "Little",
  "Very Mild",
  "Discomforting",
  "Tolerable",
  "Distressing",
  "Very Distressing",
  "Intense",
  "Very Intense",
  "Utterly Horrible",
  "Unbearable",
  "Horrendous"
];
var painItems = [
  "Aching",
  "Burning",
  "Crawling",
  "Crushing",
  "Heaviness", 
  "Icy coldness", 
  "Intermittent",
  "Numbing" ,
  "Piercing" ,
  "Pounding", 
  "Pressure", 
  "Sharp", 
  "Shooting", 
  "Sore", 
  "Stabbing", 
  "Searing",
  "Tearing", 
  "Tenderness", 
  "Tightness",
  "Tingling" 
];


// FOOD CONSTANTS

var whomItems = [
  "Alone",
  "Colleagues",
  "Family",
  "Friends",
];

var symptomItems = [
  "None",
  "Anxiety",
  "Asthma",
  "Bloating",
  "Constipation",
  "Diarrhea",
  "Eczema",
  "Fatigue",
  "Flushing skin", 
  "Gas",
  "Hay Fever",
  "Headache",
  "Heartburn",
  "Hives",
  "Indigestion",
  "Insomnia",
  "Jitters",
  "Joint pain",
  "Mouth Ulcers",
  "Nausea",
  "Nervousness",
  "Rapid heartbeat",
  "Rash",
  "Reflux",  
  "Restlessness",
  "Sinus",
  "Stomach upset",
  "Vomiting",
];

var moodItems = [
  "Angry",
  "Bored",
  "Depressed",
  "Happy",
  "Hesitant",
  "Lethargic",
  "Neutral",
  "Positive",
  "Rushed",
  "Tired",
  "Vulnerable",
];

//MOVEMENT CONSTANTS

var timeItems = [
  "< 10 minutes",
  "Between 10 to 30 minutes",
  "Between 30 minutes to 1 hour",
  "> 1 hour",
];
var moveItems = [
  "Aerobic",
  "Anaerobic",
  "Aqua fitness classes",
  "Cycling",
  "High intensity interval training",
  "Hydrotherapy",
  "Jogging / running",
  "Martial arts",
  "Organised team sports",
  "Pilates",
  "Resistance training",
  "Stretching",
  "Swimming",
  "Tai Chi",
  "Walking",
  "Yoga",
];

//MEDICATIONS

var medicineList = [
  "Agomelatine",
  "Amantadine",
  "Amitriptyline",
  "Baclofen",
  "Capsaicin",
  "Carbamazepine",
  "Celecoxib",
  "Citalopram",
  "Clomipramine",
  "Clonidine",
  "Codeine",
  "Desvenlafaxine",
  "Diclofenac",
  "Dothiepin",
  "Doxepin",
  "Escitalopram",
  "Duloxetine",
  "Fentanyl",
  "Fluoxetine",
  "Fluvoxamine",
  "Gabapentin",
  "Hydromorphone",
  "Ibuprofen",
  "Imiprimine",
  "Ketamine",
  "Lamotrigine",
  "Lignocaine",
  "Lyrica",
  "Magnesium",
  "Meloxicam",
  "Memantine",
  "Methadone",
  "Mianserin",
  "Mirtazapine",
  "Moclobemide",
  "Morphine",
  "Naproxen",
  "Nortriptyline",
  "Orphenadrine",
  "Oxycodone",
  "Oxcarbamazepine",
  "Palmitoylethanolamide",
  "Paracetamol",
  "Palexia",
  "Paroxetine",
  "Phenelzine",
  "Pregabalin",
  "Reboxetine",
  "Sertraline",
  "Tapentadol",
  "Topiramate",
  "Topiramate",
  "Tramandol",
  "Tranylcypromine",
  "Trimipramine",
  "Valproate",
  "Venlafaxine",
  "Venlafaxine",
  "Vortioxetine",
];